bespoken/virtual-device-sdk

- .editorconfig
- package.json
- src/SilentEchoScript.ts
- src/SilentEchoValidator.ts
- test/SilentEchoScriptTest.ts
- test/SilentEchoTest.ts
- test/SilentEchoValidatorTest.ts
- test/fixtures.ts
> SilentEchoScript & SilentEchoValidator improvements

- package.json
- src/Index.ts
- src/SilentEchoScript.ts
- test/SilentEchoScriptTest.ts
> src: api improvements

- src/SilentEchoScript.ts
- test/SilentEchoScriptTest.ts
- Improvements on checking beginning/ending blank lines.
> script: improvements

- package.json
package: 0.2.4 release
Includes:
- validator: removes 10s delay @ https://github.com/bespoken/silent-echo-sdk/pull/20
> package version: 0.2.4

- src/SilentEchoScript.ts
- test/SilentEchoScriptTest.ts
- SilentEchoScript: Fix for showing correctly heading spinner.
> {src,test}: fix heading spinner

- package.json
- npm: published v0.3.2 
- package: released v0.3.2
- Includes:
- optional params fixes @ https://github.com/bespoken/silent-echo-sdk/pull/26
- callbacks support @ https://github.com/bespoken/silent-echo-sdk/pull/23
- wildcards support @ https://github.com/bespoken/silent-echo-sdk/pull/22
- improvements on silent echo script html @ https://github.com/bespoken/silent-echo-sdk/pull/25
> package: v0.3.2

- package.json
- package: adds preversion
- closes: https://github.com/bespoken/silent-echo-sdk/issues/33
> package: v0.3.5 & adds preversion

- package.json
- src/Index.ts
- src/SilentEchoScript.ts
- src/SilentEchoValidator.ts
- test/SilentEchoScriptTest.ts
- package: update version to match latest npm release.
- SilentEchoScript: support for passing context to callbacks.
> SMAPI improvements

- package.json
- src/SilentEchoValidator.ts
- SilentEchoValidator: adds better feedback when user cannot invoke a skill.
- Closes: https://github.com/bespoken/dashboard/issues/477
> SilentEchoValidator: better feedback

- README.md
- package.json
- src/Index.ts
- src/VirtualDevice.ts
- src/VirtualDeviceScript.ts
- src/VirtualDeviceValidator.ts
- test/VirtualDeviceScriptTest.ts
- test/VirtualDeviceTest.ts
- test/VirtualDeviceValidatorTest.ts
- test/fixtures.ts
- Renames:
- README: Changes SilentEcho* to VirtualDevice*.
- Closes: https://github.com/bespoken/silent-echo-sdk/issues/28
- Unit test
> src: renaming SilentEcho* -> VirtualDevice*

- package.json
- src/VirtualDeviceScript.ts
- test/VirtualDeviceScriptTest.ts
- VirtualDeviceScript: adds improvements when detecting invocation name:
- Adds case-insensitive for invocation naming keywords
- Extending invocation name keywords, now valid: `launch`, `tell` and `ask`.
- package.json: updates version to minor release: `1.1.0`.
- Closes: #48
> {src,test}: improves detect invocation name

- package.json
- src/ConsolePrinter.ts
- src/VirtualDeviceValidator.ts
- src/YAMLParser.ts
- test/ConsolePrinterTest.ts
- test/VirtualDeviceScriptTest.ts
- test/YAMLParserTest.ts
Small enhancements for writing scripts and using the test runner
> Small enhancements to scripts

- package.json
- src/BatchValidator.ts
- src/ConsolePrinter.ts
- src/ScriptRunner.ts
Batch prints results of sequences as it goes
Removed truncation on property name
Removed final print out at the end
> Improved batch runs

- src/BatchValidator.ts
- src/SequencedValidator.ts
Prevents exceptions and empty messages in the ConsolePrinter.
> Creates a default error when an exception is thrown

- src/VirtualDevice.ts
- src/VirtualDeviceValidator.ts
- test/BatchValidatorTest.ts
- test/ConsolePrinterTest.ts
- test/MessageMock.ts
- test/VirtualDeviceScriptTest.ts
- test/VirtualDeviceTest.ts
Automatically replaces homophones of a word with the expected word - makes up for ASR issues
> Adds homophone support

- src/VirtualDevice.ts
- test/BatchValidatorTest.ts
- test/SequencedValidatorTest.ts
- test/VirtualDeviceScriptTest.ts
- test/VirtualDeviceTest.ts
relates https://github.com/bespoken/bst/issues/473
Removes the word "alexa" from one word utterances.
> Removes "alexa" in front of short utterances

- src/VirtualDevice.ts
- test/MessageMock.ts
- test/VirtualDeviceTest.ts
> Get conversation results from async batch process

- package.json
- src/VirtualDevice.ts
- test/MessageMock.ts
- test/VirtualDeviceTest.ts
Relates to https://github.com/bespoken/skill-testing-ml/issues/226
> UUID management for async mode

- src/VirtualDevice.ts
- test/VirtualDeviceTest.ts
> FEAT-138: Treat homophones as lowercase

- package-lock.json
- package.json
- src/VirtualDevice.ts
- test/MessageMock.ts
- test/VirtualDeviceTest.ts
- tsconfig.json
Relates to https://github.com/bespoken/skill-testing-ml/issues/322
> Reject complete error on async mode

- .circleci/config.yml
- package-lock.json
- package.json
- src/VirtualDevice.ts
- test/MessageMock.ts
- test/PrettyPrinterTest.ts
- test/VirtualDeviceTest.ts
Relates to https://github.com/bespoken/bst/issues/602
- Add HTTP_PROXY option for virtual-device-sdk
> Add support for HTTPS_PROXY

- .circleci/config.yml
- package-lock.json
- package.json
- src/VirtualDevice.ts
- test/VirtualDeviceTest.ts
Relates to https://github.com/bespoken/skill-testing-ml/issues/390﻿
> Add function to filter the requests in batch process

- package-lock.json
- package.json
- src/VirtualDevice.ts
Fixes a bad dependency (it was looking for https_proxy_agent inside http_proxy_agent)
> dependency fix

- src/VirtualDevice.ts
Set debug param for batchMessage and message functions in the path
Related to https://github.com/bespoken/skill-testing-ml/issues/433
> Set debug param
